<?php

namespace ContainerOjaEbaO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitializeEmailTemplatesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\InitializeEmailTemplatesCommand' shared autowired service.
     *
     * @return \App\Command\InitializeEmailTemplatesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/InitializeEmailTemplatesCommand.php';

        $container->privates['App\\Command\\InitializeEmailTemplatesCommand'] = $instance = new \App\Command\InitializeEmailTemplatesCommand(($container->privates['App\\Service\\EmailTemplateService'] ?? $container->load('getEmailTemplateServiceService')));

        $instance->setName('app:initialize-email-templates');
        $instance->setDescription('Initialize default email templates in database');

        return $instance;
    }
}
