<?php

namespace ContainerNs7WWaw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitializeEmailTemplatesCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\InitializeEmailTemplatesCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\InitializeEmailTemplatesCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:initialize-email-templates', [], 'Initialize default email templates in database', false, #[\Closure(name: 'App\\Command\\InitializeEmailTemplatesCommand')] fn (): \App\Command\InitializeEmailTemplatesCommand => ($container->privates['App\\Command\\InitializeEmailTemplatesCommand'] ?? $container->load('getInitializeEmailTemplatesCommandService')));
    }
}
