symfonycasts_reset_password:
    # Activer la collecte des donnees obsoletes
    enable_garbage_collection: true

    # Duree de vie des requetes de reinitialisation de mot de passe (en secondes)
    lifetime: 3600 # 1 heure

    # Utiliser le repository de requetes de reinitialisation de mot de passe
    request_password_repository: App\Repository\ResetPasswordRequestRepository

    # Limiter le nombre de requetes de reinitialisation par utilisateur
    throttle_limit: 3 # 3 requetes maximum