<?php

namespace ContainerX0mx8H8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserPermissionsFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\UserPermissionsFormType' shared autowired service.
     *
     * @return \App\Form\UserPermissionsFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/UserPermissionsFormType.php';

        return $container->privates['App\\Form\\UserPermissionsFormType'] = new \App\Form\UserPermissionsFormType(($container->services['translator'] ?? $container->load('getTranslatorService')));
    }
}
