<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'approvedAt' => [parent::class, 'approvedAt', null, 16],
        "\0".parent::class."\0".'birthDate' => [parent::class, 'birthDate', null, 16],
        "\0".parent::class."\0".'boxNumber' => [parent::class, 'boxNumber', null, 16],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null, 16],
        "\0".parent::class."\0".'country' => [parent::class, 'country', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'emailVerifiedAt' => [parent::class, 'emailVerifiedAt', null, 16],
        "\0".parent::class."\0".'firstName' => [parent::class, 'firstName', null, 16],
        "\0".parent::class."\0".'houseNumber' => [parent::class, 'houseNumber', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isApproved' => [parent::class, 'isApproved', null, 16],
        "\0".parent::class."\0".'isVerified' => [parent::class, 'isVerified', null, 16],
        "\0".parent::class."\0".'lastLoginAt' => [parent::class, 'lastLoginAt', null, 16],
        "\0".parent::class."\0".'lastName' => [parent::class, 'lastName', null, 16],
        "\0".parent::class."\0".'locale' => [parent::class, 'locale', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'phoneNumber' => [parent::class, 'phoneNumber', null, 16],
        "\0".parent::class."\0".'postalCode' => [parent::class, 'postalCode', null, 16],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null, 16],
        "\0".parent::class."\0".'street' => [parent::class, 'street', null, 16],
        "\0".parent::class."\0".'username' => [parent::class, 'username', null, 16],
        'approvedAt' => [parent::class, 'approvedAt', null, 16],
        'birthDate' => [parent::class, 'birthDate', null, 16],
        'boxNumber' => [parent::class, 'boxNumber', null, 16],
        'city' => [parent::class, 'city', null, 16],
        'country' => [parent::class, 'country', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'emailVerifiedAt' => [parent::class, 'emailVerifiedAt', null, 16],
        'firstName' => [parent::class, 'firstName', null, 16],
        'houseNumber' => [parent::class, 'houseNumber', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isApproved' => [parent::class, 'isApproved', null, 16],
        'isVerified' => [parent::class, 'isVerified', null, 16],
        'lastLoginAt' => [parent::class, 'lastLoginAt', null, 16],
        'lastName' => [parent::class, 'lastName', null, 16],
        'locale' => [parent::class, 'locale', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'phoneNumber' => [parent::class, 'phoneNumber', null, 16],
        'postalCode' => [parent::class, 'postalCode', null, 16],
        'roles' => [parent::class, 'roles', null, 16],
        'street' => [parent::class, 'street', null, 16],
        'username' => [parent::class, 'username', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
