<?php

namespace Container2Oo3MLt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PUsP4l5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PUsP4l5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PUsP4l5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'template' => ['privates', '.errored..service_locator.PUsP4l5.App\\Entity\\EmailTemplate', NULL, 'Cannot autowire service ".service_locator.PUsP4l5": it needs an instance of "App\\Entity\\EmailTemplate" but this type has been excluded in "config/services.yaml".'],
            'templateRepository' => ['privates', 'App\\Repository\\EmailTemplateRepository', 'getEmailTemplateRepositoryService', true],
            'translator' => ['services', 'translator', 'getTranslatorService', true],
        ], [
            'template' => 'App\\Entity\\EmailTemplate',
            'templateRepository' => 'App\\Repository\\EmailTemplateRepository',
            'translator' => '?',
        ]);
    }
}
