<?php

namespace Container2Oo3MLt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_ANKFIv4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.ANKFIv4' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/MessageHandler/SendEmailMessageHandler.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['.messenger.handler_descriptor.ANKFIv4'])) {
            return $container->privates['.messenger.handler_descriptor.ANKFIv4'];
        }

        return $container->privates['.messenger.handler_descriptor.ANKFIv4'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\MessageHandler\SendEmailMessageHandler($a, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'))), []);
    }
}
