<?php

namespace Container2Oo3MLt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerapproveUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Dw6dywA.App\Controller\AdminController::approveUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Dw6dywA.App\\Controller\\AdminController::approveUser()'] = ($container->privates['.service_locator.Dw6dywA'] ?? $container->load('get_ServiceLocator_Dw6dywAService'))->withContext('App\\Controller\\AdminController::approveUser()', $container);
    }
}
