<?php

namespace Container2Oo3MLt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebug_ErrorHandlerConfiguratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'debug.error_handler_configurator' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Debug\ErrorHandlerConfigurator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Debug/ErrorHandlerConfigurator.php';

        $a = new \Monolog\Logger('php');
        $a->pushHandler(($container->privates['monolog.handler.console'] ?? self::getMonolog_Handler_ConsoleService($container)));
        $a->pushHandler(($container->privates['monolog.handler.emergency_file'] ?? self::getMonolog_Handler_EmergencyFileService($container)));
        $a->pushHandler(($container->privates['monolog.handler.alert_file'] ?? self::getMonolog_Handler_AlertFileService($container)));
        $a->pushHandler(($container->privates['monolog.handler.critical_file'] ?? self::getMonolog_Handler_CriticalFileService($container)));
        $a->pushHandler(($container->privates['monolog.handler.error_file'] ?? self::getMonolog_Handler_ErrorFileService($container)));
        $a->pushHandler(($container->privates['monolog.handler.warning_file'] ?? self::getMonolog_Handler_WarningFileService($container)));
        $a->pushHandler(($container->privates['monolog.handler.notice_file'] ?? self::getMonolog_Handler_NoticeFileService($container)));
        $a->pushHandler(($container->privates['monolog.handler.info_file'] ?? self::getMonolog_Handler_InfoFileService($container)));
        $a->pushHandler(($container->privates['monolog.handler.debug_file'] ?? self::getMonolog_Handler_DebugFileService($container)));
        $a->pushHandler(($container->privates['monolog.handler.main'] ?? self::getMonolog_Handler_MainService($container)));

        return $container->services['debug.error_handler_configurator'] = new \Symfony\Component\HttpKernel\Debug\ErrorHandlerConfigurator($a, NULL, -1, true, true, ($container->services['monolog.logger.deprecation'] ?? $container->load('getMonolog_Logger_DeprecationService')));
    }
}
