<?php

namespace Container2Oo3MLt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailTemplate2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vOrWoox.App\Entity\EmailTemplate' shared service.
     *
     * @return \App\Entity\EmailTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.vOrWoox": it needs an instance of "App\\Entity\\EmailTemplate" but this type has been excluded in "config/services.yaml".');
    }
}
