<?php

namespace Container2Oo3MLt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailTemplateControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PUsP4l5.App\Controller\EmailTemplateController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PUsP4l5.App\\Controller\\EmailTemplateController::delete()'] = ($container->privates['.service_locator.PUsP4l5'] ?? $container->load('get_ServiceLocator_PUsP4l5Service'))->withContext('App\\Controller\\EmailTemplateController::delete()', $container);
    }
}
