<?php

namespace Container2Oo3MLt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailTemplateControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k9R1AxW.App\Controller\EmailTemplateController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.k9R1AxW.App\\Controller\\EmailTemplateController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'templateRepository' => ['privates', 'App\\Repository\\EmailTemplateRepository', 'getEmailTemplateRepositoryService', true],
        ], [
            'templateRepository' => 'App\\Repository\\EmailTemplateRepository',
        ]))->withContext('App\\Controller\\EmailTemplateController::index()', $container);
    }
}
