<?php

namespace Container2Oo3MLt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailTemplateControllerpreviewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vOrWoox.App\Controller\EmailTemplateController::preview()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vOrWoox.App\\Controller\\EmailTemplateController::preview()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'template' => ['privates', '.errored..service_locator.vOrWoox.App\\Entity\\EmailTemplate', NULL, 'Cannot autowire service ".service_locator.vOrWoox": it needs an instance of "App\\Entity\\EmailTemplate" but this type has been excluded in "config/services.yaml".'],
        ], [
            'template' => 'App\\Entity\\EmailTemplate',
        ]))->withContext('App\\Controller\\EmailTemplateController::preview()', $container);
    }
}
