<?php

namespace Container2Oo3MLt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailTemplateControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.suHSJ1C.App\Controller\EmailTemplateController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.suHSJ1C.App\\Controller\\EmailTemplateController::new()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'templateRepository' => ['privates', 'App\\Repository\\EmailTemplateRepository', 'getEmailTemplateRepositoryService', true],
            'translator' => ['services', 'translator', 'getTranslatorService', true],
        ], [
            'templateRepository' => 'App\\Repository\\EmailTemplateRepository',
            'translator' => '?',
        ]))->withContext('App\\Controller\\EmailTemplateController::new()', $container);
    }
}
