<?php

namespace Container2Oo3MLt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailTemplateServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\EmailTemplateService' shared autowired service.
     *
     * @return \App\Service\EmailTemplateService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/EmailTemplateService.php';

        return $container->privates['App\\Service\\EmailTemplateService'] = new \App\Service\EmailTemplateService(($container->privates['App\\Repository\\EmailTemplateRepository'] ?? $container->load('getEmailTemplateRepositoryService')), ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), ($container->privates['twig'] ?? $container->load('getTwigService')), ($container->services['translator'] ?? $container->load('getTranslatorService')), 'fr', $container->getEnv('APP_EMAIL'), $container->getEnv('APP_DOMAIN'));
    }
}
