<?php

namespace Container2Oo3MLt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileControllerchangePasswordService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q.g4ps2.App\Controller\ProfileController::changePassword()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q.g4ps2.App\\Controller\\ProfileController::changePassword()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'translator' => ['services', 'translator', 'getTranslatorService', true],
        ], [
            'passwordHasher' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
            'translator' => '?',
        ]))->withContext('App\\Controller\\ProfileController::changePassword()', $container);
    }
}
