<?php

namespace Container2Oo3MLt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStaticTranslationControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KHhLDTq.App\Controller\StaticTranslationController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KHhLDTq.App\\Controller\\StaticTranslationController::edit()'] = ($container->privates['.service_locator.KHhLDTq'] ?? $container->load('get_ServiceLocator_KHhLDTqService'))->withContext('App\\Controller\\StaticTranslationController::edit()', $container);
    }
}
