<?php

namespace Container2Oo3MLt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStaticTranslationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\StaticTranslationController' shared autowired service.
     *
     * @return \App\Controller\StaticTranslationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/StaticTranslationController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/StaticTranslationService.php';

        $container->services['App\\Controller\\StaticTranslationController'] = $instance = new \App\Controller\StaticTranslationController(($container->privates['App\\Service\\AdminPermissionService'] ?? $container->load('getAdminPermissionServiceService')), new \App\Service\StaticTranslationService(\dirname(__DIR__, 4), $container->parameters['app.locales']));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\StaticTranslationController', $container));

        return $instance;
    }
}
