<?php

namespace Container2Oo3MLt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTranslationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TranslationController' shared autowired service.
     *
     * @return \App\Controller\TranslationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/TranslationController.php';

        $container->services['App\\Controller\\TranslationController'] = $instance = new \App\Controller\TranslationController(($container->privates['App\\Service\\AdminPermissionService'] ?? $container->load('getAdminPermissionServiceService')), ($container->privates['App\\Service\\DynamicTranslatorService'] ?? $container->load('getDynamicTranslatorServiceService')), ($container->services['translator'] ?? $container->load('getTranslatorService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\TranslationController', $container));

        return $instance;
    }
}
