<?php

namespace Container2Oo3MLt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserLocaleListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\UserLocaleListener' shared autowired service.
     *
     * @return \App\EventListener\UserLocaleListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/UserLocaleListener.php';

        return $container->privates['App\\EventListener\\UserLocaleListener'] = new \App\EventListener\UserLocaleListener(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
