<?php

namespace ContainerAxoQTqp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserPermissionsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\UserPermissionsController' shared autowired service.
     *
     * @return \App\Controller\Admin\UserPermissionsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/UserPermissionsController.php';

        $container->services['App\\Controller\\Admin\\UserPermissionsController'] = $instance = new \App\Controller\Admin\UserPermissionsController(($container->privates['App\\Service\\AdminPermissionService'] ?? $container->load('getAdminPermissionServiceService')), ($container->privates['App\\Repository\\AdminPermissionRepository'] ?? $container->load('getAdminPermissionRepositoryService')), ($container->privates['App\\Service\\EmailTemplateService'] ?? $container->load('getEmailTemplateServiceService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Admin\\UserPermissionsController', $container));

        return $instance;
    }
}
