<?php

namespace ContainerCkqBpYf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileControllerchangePasswordService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ED6v._R.App\Controller\ProfileController::changePassword()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ED6v._R.App\\Controller\\ProfileController::changePassword()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.ED6v._R.Symfony\\Component\\Security\\Core\\User\\PasswordAuthenticatedUserInterface', NULL, 'Cannot autowire service ".service_locator.ED6v._R": it references interface "Symfony\\Component\\Security\\Core\\User\\PasswordAuthenticatedUserInterface" but no such service exists. Did you create an instantiable class that implements this interface?'],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'user' => 'Symfony\\Component\\Security\\Core\\User\\PasswordAuthenticatedUserInterface',
            'passwordHasher' => '?',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\ProfileController::changePassword()', $container);
    }
}
