<?php

namespace ContainerYEAWZqc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailTemplateServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\EmailTemplateService' shared autowired service.
     *
     * @return \App\Service\EmailTemplateService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/EmailTemplateService.php';

        return $container->privates['App\\Service\\EmailTemplateService'] = new \App\Service\EmailTemplateService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\EmailTemplateRepository'] ?? $container->load('getEmailTemplateRepositoryService')), ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService')), ($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)), ($container->privates['twig'] ?? $container->load('getTwigService')), ($container->services['translator'] ?? $container->load('getTranslatorService')));
    }
}
