<?php

namespace ContainerYEAWZqc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationControllerregisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iWwUsxu.App\Controller\RegistrationController::register()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iWwUsxu.App\\Controller\\RegistrationController::register()'] = ($container->privates['.service_locator.iWwUsxu'] ?? $container->load('get_ServiceLocator_IWwUsxuService'))->withContext('App\\Controller\\RegistrationController::register()', $container);
    }
}
