<?php

namespace ContainerR2fUmkB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileControllerchangePasswordService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iWwUsxu.App\Controller\ProfileController::changePassword()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.iWwUsxu'] ?? $container->load('get_ServiceLocator_IWwUsxuService'));

        if (isset($container->privates['.service_locator.iWwUsxu.App\\Controller\\ProfileController::changePassword()'])) {
            return $container->privates['.service_locator.iWwUsxu.App\\Controller\\ProfileController::changePassword()'];
        }

        return $container->privates['.service_locator.iWwUsxu.App\\Controller\\ProfileController::changePassword()'] = $a->withContext('App\\Controller\\ProfileController::changePassword()', $container);
    }
}
