<?php

namespace ContainerAj0ZvQx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuditLogServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\AuditLogService' shared autowired service.
     *
     * @return \App\Service\AuditLogService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/AuditLogService.php';

        return $container->privates['App\\Service\\AuditLogService'] = new \App\Service\AuditLogService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
