<?php

namespace Container7EPoNxt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuperAdminControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SuperAdminController' shared autowired service.
     *
     * @return \App\Controller\SuperAdminController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/SuperAdminController.php';

        $container->services['App\\Controller\\SuperAdminController'] = $instance = new \App\Controller\SuperAdminController(($container->privates['App\\Service\\AdminPermissionService'] ?? $container->load('getAdminPermissionServiceService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->services['translator'] ?? $container->load('getTranslatorService')), ($container->privates['App\\Service\\EmailTemplateService'] ?? $container->load('getEmailTemplateServiceService')), ($container->privates['App\\Service\\AuditLogService'] ?? $container->load('getAuditLogServiceService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\SuperAdminController', $container));

        return $instance;
    }
}
