<?php

namespace Container6vcZSLA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailTemplateControllereditLocaleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sZGeO9P.App\Controller\EmailTemplateController::editLocale()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sZGeO9P.App\\Controller\\EmailTemplateController::editLocale()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'template' => ['privates', '.errored..service_locator.sZGeO9P.App\\Entity\\EmailTemplate', NULL, 'Cannot autowire service ".service_locator.sZGeO9P": it needs an instance of "App\\Entity\\EmailTemplate" but this type has been excluded in "config/services.yaml".'],
            'templateRepository' => ['privates', 'App\\Repository\\EmailTemplateRepository', 'getEmailTemplateRepositoryService', true],
        ], [
            'template' => 'App\\Entity\\EmailTemplate',
            'templateRepository' => 'App\\Repository\\EmailTemplateRepository',
        ]))->withContext('App\\Controller\\EmailTemplateController::editLocale()', $container);
    }
}
