<?php

namespace Container6vcZSLA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserPermissionsControllermanagePermissionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WkfvUVe.App\Controller\Admin\UserPermissionsController::managePermissions()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WkfvUVe.App\\Controller\\Admin\\UserPermissionsController::managePermissions()'] = ($container->privates['.service_locator.WkfvUVe'] ?? $container->load('get_ServiceLocator_WkfvUVeService'))->withContext('App\\Controller\\Admin\\UserPermissionsController::managePermissions()', $container);
    }
}
