<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6vcZSLA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6vcZSLA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6vcZSLA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6vcZSLA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6vcZSLA\App_KernelDevDebugContainer([
    'container.build_hash' => '6vcZSLA',
    'container.build_id' => 'bfa25aa0',
    'container.build_time' => 1744744232,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container6vcZSLA');
