<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRtv8Enz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRtv8Enz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRtv8Enz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRtv8Enz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRtv8Enz\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rtv8Enz',
    'container.build_id' => '012e0b5a',
    'container.build_time' => 1744760212,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRtv8Enz');
