<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWlYvEBX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWlYvEBX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWlYvEBX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWlYvEBX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWlYvEBX\App_KernelDevDebugContainer([
    'container.build_hash' => 'WlYvEBX',
    'container.build_id' => 'eb963205',
    'container.build_time' => 1744195244,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWlYvEBX');
